version: 2

models:
  - name: silver_adhesion_detail
    columns:
      - name: silver_id
        tests:
          - unique
          - not_null
      - name: num_adhesion_normalise
        tests:
          - not_null
      - name: num_beneficiaire_unique
        tests:
          - not_null
      - name: exercice_paiement
        tests:
          - not_null
      - name: type_beneficiaire
        tests:
          - not_null
          - accepted_values:
              values: ["AS", "CO", "EN"]
      - name: type_beneficiaire_libelle
        tests:
          - not_null
      - name: categ_formule
        tests:
          - not_null
      - name: primes_acquises
        tests:
          - not_null
      - name: age
        tests:
          - not_null
      - name: gp_age
        tests:
          - not_null

  - name: silver_beneficiaire
    columns:
      - name: silver_id
        tests:
          - unique
          - not_null
      - name: num_beneficiaire
        tests:
          - not_null
      - name: sexe
        tests:
          - not_null
          - accepted_values:
              values: ["Homme", "Femme"]
      - name: regime_social
        tests:
          - not_null

  - name: silver_prestations_sante
    columns:
      - name: silver_id
        tests:
          - unique
          - not_null
      - name: num_sinistre
        tests:
          - not_null
      - name: num_adhesion
        tests:
          - not_null
      - name: frais_reel
        tests:
          - not_null
      - name: montant_secu
        tests:
          - not_null
      - name: montant_rembourse
        tests:
          - not_null

  - name: silver_dept_region
    columns:
      - name: silver_id
        tests:
          - unique
          - not_null
      - name: cp
        tests:
          - not_null
      - name: departement
        tests:
          - not_null
      - name: region
        tests:
          - not_null

  - name: silver_meteo
    columns:
      - name: silver_id
        tests:
          - unique
          - not_null
      - name: cp
        tests:
          - not_null
      - name: temperature
        tests:
          - not_null

  - name: silver_contrat
    columns:
      - name: silver_id
        tests:
          - unique
          - not_null
      - name: num_adhesion_normalise
        tests:
          - not_null
      - name: categ_formule
        tests:
          - not_null
      - name: code_profession
        tests:
          - not_null
