{{ config(materialized='table') }}

WITH raw_adhesion AS (
    SELECT * FROM {{ source('raw_bronze', 'bronze_adhesion_detail') }}
),

cleaned_data AS (
    SELECT
        CAST(NUM_ADHESION_NORMALISE AS VARCHAR(100)) AS NUM_ADHESION_NORMALISE,
        CAST(NUM_BENEFICIAIRE_UNIQUE AS INTEGER) AS NUM_BENEFICIAIRE_UNIQUE,
        CAST(CODE_POSTAL AS INTEGER) AS CODE_POSTAL,
        CAST(EXERCICE_PAIEMENT AS INTEGER) AS EXERCICE_PAIEMENT,
        CAST(NUM_BENEFICIAIRE AS INTEGER) AS NUM_BENEFICIAIRE,
        TYPE_BENEFICIAIRE,
        CODE_PRODUIT,
        CODE_FRACTIONNEMENT,
        TO_DATE(DATE_NAISSANCE_ASSURE, 'DD/MM/YYYY') AS DATE_NAISSANCE_ASSURE,
        TO_DATE(DATE_NAISSANCE_BENEFICIAIRE, 'DD/MM/YYYY') AS DATE_NAISSANCE_BENEFICIAIRE,
        UPPER(CODE_PROFESSION) AS CODE_PROFESSION,
        CODE_GARANTIE,
        TRIM(REGEXP_REPLACE(FORMULE, '\s+', ' ')) AS FORMULE,
        CAST(REPLACE(CAST(PRIMES_ACQUISES AS TEXT), ',', '.') AS FLOAT) AS PRIMES_ACQUISES,
        CAST(CODE_AGENT AS BIGINT) AS CODE_AGENT,
        CAST(CODE_REGION AS INTEGER) AS CODE_REGION,
        CASE
            WHEN PRIME_GARANTIE = 'Non' THEN 0
            WHEN PRIME_GARANTIE = 'Oui' THEN 1
        END AS PRIME_GARANTIE
    FROM raw_adhesion
)

SELECT *
FROM cleaned_data
WHERE DATE_NAISSANCE_BENEFICIAIRE IS NOT NULL
  AND EXERCICE_PAIEMENT IS NOT NULL
  AND (EXERCICE_PAIEMENT - EXTRACT(YEAR FROM DATE_NAISSANCE_BENEFICIAIRE)) >= 0